architecture: YOLOv5 # YOLOv6 is based on YOLOv5
norm_type: sync_bn
use_ema: True
ema_decay: 0.9999
ema_decay_type: "exponential"
act: silu
find_unused_parameters: True

depth_mult: 1.0
width_mult: 1.0

YOLOv5:
  backbone: CSPBepBackbone
  neck: CSPRepPAN
  yolo_head: EffiDeHead
  post_process: ~

CSPBepBackbone:
  return_idx: [2, 3, 4]
  depthwise: false
  csp_e: 0.5

CSPRepPAN:
  depthwise: false
  csp_e: 0.5

EffiDeHead:
  depthwise: false
  iou_type: 'siou'
  assigner:
    name: SimOTAAssigner
    candidate_topk: 10
    use_vfl: False
  nms:
    name: MultiClassNMS
    nms_top_k: 10000
    keep_top_k: 300
    score_threshold: 0.001
    nms_threshold: 0.65
