architecture: YOLOv7
norm_type: sync_bn
use_ema: True
ema_decay: 0.9999
ema_decay_type: "exponential"
act: silu
find_unused_parameters: True

depth_mult: 1.0 # no use in YOLOv7
width_mult: 1.0

arch: 'L'
use_aux: False
use_implicit: True

YOLOv7:
  backbone: ELANNet
  neck: ELANFPN
  yolo_head: YOLOv7uHead # Anchor free, like PPYOLOE/YOLOv6/YOLOv8 Head
  post_process: ~

ELANNet:
  return_idx: [2, 3, 4]
  depthwise: false

ELANFPN:
  depthwise: false
  for_u6: True #

YOLOv7uHead:
  fpn_strides: [8, 16, 32]
  loss_weight: {class: 0.5, iou: 7.5, dfl: 1.5}
  assigner:
    name: TaskAlignedAssigner
    topk: 10
    alpha: 0.5
    beta: 6.0
  nms:
    name: MultiClassNMS
    nms_top_k: 3000
    keep_top_k: 300
    score_threshold: 0.001
    nms_threshold: 0.7
