architecture: YOLOv8
norm_type: sync_bn
use_ema: True
ema_decay: 0.9999
ema_decay_type: "exponential"
act: silu
find_unused_parameters: True

depth_mult: 1.0 # default: L version
width_mult: 1.0

YOLOv8:
  backbone: YOLOv8CSPDarkNet
  neck: YOLOv8CSPPANP6
  yolo_head: YOLOv8Head
  post_process: ~

YOLOv8CSPDarkNet:
  arch: 'P6'
  return_idx: [2, 3, 4, 5]
  last_stage_ch: 1024
  last2_stage_ch: 768

# use default config
# YOLOv8CSPPANP6:

YOLOv8Head:
  fpn_strides: [8, 16, 32, 64]
  loss_weight: {class: 0.5, iou: 7.5, dfl: 1.5}
  assigner:
    name: TaskAlignedAssigner
    topk: 10
    alpha: 0.5
    beta: 6.0
  nms:
    name: MultiClassNMS
    nms_top_k: 1000
    keep_top_k: 300
    score_threshold: 0.001
    nms_threshold: 0.7
