_BASE_: [
  '../datasets/rice80_voc.yml',
  '../runtime.yml',
  '_base_/optimizer_500e.yml',
  '_base_/yolov8_cspdarknet.yml',
  '_base_/yolov8_reader.yml',
]
depth_mult: 0.33
width_mult: 0.25

log_iter: 10
snapshot_epoch: 1
epoch: 100 

pretrain_weights: https://paddledet.bj.bcebos.com/models/yolov8_n_500e_coco.pdparams
weights: output/yolov8_n_100e_64b8b_rice80/model_final 

LearningRate:
  base_lr: 0.0001  
  schedulers:
  - !CosineDecay
    max_epochs: 100
  - !LinearWarmup
    start_factor: 0.
    epochs: 5

OptimizerBuilder:
  optimizer:
    momentum: 0.937
    type: Momentum
  regularizer:
    factor: 0.0005  
    type: L2

TrainReader:
  batch_size: 64

EvalReader:
  batch_size: 8
