_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_300e_high.yml',
  '_base_/yolov8_cspdarknet.yml',
  '_base_/yolov8_reader_high_aug.yml',
]
arch: 'X'
depth_mult: 1.0 # not 1.33
width_mult: 1.25

log_iter: 100
snapshot_epoch: 10
weights: output/yolov8_x_300e_coco/model_final


TrainReader:
  batch_size: 16 # default 8 gpus, total bs = 128


YOLOv5Loss:
  obj_weight: 0.7
  cls_weght: 0.3
