_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_400e.yml',
  '_base_/yolov6mt_efficientrep.yml',
  '_base_/yolov6mt_reader_416.yml',
]
depth_mult: 0.33
width_mult: 0.25

log_iter: 100
snapshot_epoch: 10
weights: output/yolov6mt_n_416_400e_coco/model_final


EffiDeHead:
  iou_type: 'siou'
  use_dfl: False
