_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_300e.yml',
  '_base_/yolov6_efficientrep.yml',
  '_base_/yolov6_reader.yml',
]
depth_mult: 0.33
width_mult: 0.25
log_iter: 20
snapshot_epoch: 10
weights: output/yolov6_n_300e_coco/model_final


### reader config
TrainReader:
  batch_size: 32 # default 8 gpus, total bs = 128

EvalReader:
  batch_size: 1


### model config
act: 'relu'
training_mode: "repvgg"
model_type: "YOLOv6n"
YOLOv6:
  backbone: EfficientRep
  neck: RepBiFPAN
  yolo_head: EffiDeHead_fuseab
  post_process: ~

# EffiDeHead:
#   reg_max: 0
#   use_dfl: False # False in n/s
#   loss_weight: {cls: 1.0, iou: 2.5}
#   iou_type: 'siou' # only in n/t version

EffiDeHead_fuseab:
  reg_max: 0
  use_dfl: False # False in n/s
  anchors: [[10, 13, 19, 19, 33, 23],
            [ 30, 61, 59, 59, 59, 119 ],
            [ 116, 90, 185, 185, 373, 326 ] ]
  static_assigner_epoch: 4
  loss_weight: {cls: 1.0, iou: 2.5}
  iou_type: 'siou' # only in n/t version
  

### distill config
## Step 1: Training the base model, get about 37.0 mAP

## Step 2: Self-distillation training, get about 37.5 mAP

YOLOv6:
  backbone: EfficientRep
  neck: RepBiFPAN
  yolo_head: EffiDeHead_distill_ns
  post_process: ~

EffiDeHead_distill_ns:
  reg_max: 16
  use_dfl: True

### Please cancel the following comment and train again:
temperature: 20
self_distill: True
pretrain_weights: model/best_model.pdparams
save_dir: output_distill
weights: output_distill/yolov6_n_300e_coco/model_final
