_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_300e.yml',
  '_base_/yolov6_cspbep.yml',
  '_base_/yolov6_reader_high_aug.yml',
]
depth_mult: 1.0
width_mult: 1.0

log_iter: 20
snapshot_epoch: 10
weights: output/yolov6_l_silu_300e_coco/model_final


act: 'silu'
training_mode: "conv_silu" # Note: L use silu


CSPBepBackbone:
  csp_e: 0.50

CSPRepPAN:
  csp_e: 0.50

EffiDeHead:
  reg_max: 16
  use_dfl: True
  iou_type: 'giou'
  loss_weight: {cls: 1.0, iou: 2.5, dfl: 0.5, cwd: 10.0}
  distill_weight: {cls: 2.0, dfl: 1.0} # 2:1 in L-relu version, will not work default (self_distill=False)


# Step 1: Training the base model, get 51.0+ mAP
TrainReader:
  batch_size: 8 # total batch_size = 32 * gpu_num

EvalReader:
  batch_size: 4


# Step 2: Self-distillation training, get 52.0+ mAP
# Please cancel the following comment and train again
#
# self_distill: True
# pretrain_weights: output/yolov6_l_silu_300e_coco/model_final.pdparams
# save_dir: output_distill
# weights: output_distill/yolov6_l_silu_300e_coco/model_final
#
# TrainReader:
#   batch_size: 16
#
