_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_400e.yml',
  '_base_/yolov6_efficientrep.yml',
  '_base_/yolov6_reader.yml',
]
depth_mult: 0.33
width_mult: 0.375

log_iter: 20
snapshot_epoch: 10
weights: output/yolov6_t_400e_coco/model_final


EffiDeHead:
  reg_max: 0
  use_dfl: False
  loss_weight: {cls: 1.0, iou: 2.5}
  iou_type: 'siou' # only in n/t version


TrainReader:
  batch_size: 32 # total batch_size = 32 * gpu_num

EvalReader:
  batch_size: 4
