_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_300e.yml',
  '_base_/yolov7_elannet.yml',
  '_base_/yolov7_reader.yml',
]
log_iter: 100
snapshot_epoch: 10
weights: output/yolov7_x_300e_coco/model_final

arch: X


TrainReader:
  batch_size: 16
