_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_300e_tiny.yml',
  '_base_/yolov7_elannet.yml',
  '_base_/yolov7_tiny_reader.yml',
]
log_iter: 100
snapshot_epoch: 10
weights: output/yolov7_tiny_300e_coco/model_final

arch: tiny
act: LeakyReLU


TrainReader:
  batch_size: 16


YOLOv7Loss:
  box_weight: 0.05
  cls_weght: 0.5
  obj_weight: 1.0
