_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_300e.yml',
  '_base_/yolov7u_elannet.yml',
  '_base_/yolov7u_reader.yml',
]
log_iter: 100
snapshot_epoch: 10
weights: output/yolov7u_l_300e_coco/model_final

arch: L


TrainReader:
  batch_size: 8 #16 # default 8 gpus, total bs = 128
