_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  './_base_/optimizer_300e.yml',
  './_base_/rtmdet_cspnext.yml',
  './_base_/rtmdet_reader.yml',
]
depth_mult: 1.0
width_mult: 1.0

log_iter: 100
snapshot_epoch: 10
weights: output/rtmnet_l_300e_coco/model_final

RTMDetHead:
  exp_on_reg: True
