metric: COCO
num_classes: 80

TrainDataset:
  name: COCODataSet
  image_dir: train2017
  anno_path: annotations/instances_train2017.json
  dataset_dir: dataset/coco
  data_fields: ['image', 'gt_bbox', 'gt_class', 'gt_poly', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: val2017
  #anno_path: annotations/instances_val2017_1img.json
  #anno_path: annotations/instances_val2017_2img.json # pt    # pd 90.1 80.0
  #anno_path: annotations/instances_val2017_8img.json # pt 63.2 51.6    # pd 61.9 52.0   61.3 51.1
  anno_path: annotations/instances_val2017_rand24.json # pt 41.9 34.7   # pd 40.2 33.5   40.6 33.5
  #anno_path: annotations/instances_val2017.json # pt 40.5 35.4   # pd 38.9 33.8  39.3 34.0
  dataset_dir: dataset/coco
  # allow_empty: True

TestDataset:
  name: ImageFolder
  anno_path: annotations/instances_val2017.json # also support txt (like VOC's label_list.txt)
  dataset_dir: dataset/coco # if set, anno_path will be 'dataset_dir/anno_path'
