metric: COCO
num_classes: 601

# Due to the large dataset, training and evaluation are not supported currently
TrainDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/train.json
    dataset_dir: dataset/OpenImagesV7
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

# Due to the large dataset, training and evaluation are not supported currently
EvalDataset:
  !COCODataSet
    image_dir: val
    anno_path: annotations/val.json
    dataset_dir: dataset/OpenImagesV7
    allow_empty: true

TestDataset:
  !ImageFolder
    anno_path: label_list.txt
    dataset_dir: dataset/OpenImagesV7
