_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_300e.yml',
  '_base_/yolov5_cspdarknet.yml',
  '_base_/yolov5_reader.yml',
]
depth_mult: 0.33
width_mult: 0.50

log_iter: 100
snapshot_epoch: 10
weights: output/yolov5_s_80e_ssod_finetune_coco/model_final
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/yolov5_s_300e_ssod_coco.pdparams


TrainReader:
  batch_size: 16 # default 8 gpus, total bs = 128


epoch: 80
LearningRate:
  base_lr: 0.001
  schedulers:
  - !YOLOv5LRDecay
    max_epochs: 80
    min_lr_ratio: 0.01
  - !ExpWarmup
    epochs: 3

OptimizerBuilder:
  optimizer:
    type: Momentum
    momentum: 0.937
    use_nesterov: True
  regularizer:
    factor: 0.0005
    type: L2
