_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_300e_high.yml',
  '_base_/yolov5_cspdarknet.yml',
  '_base_/yolov5_reader_high_aug.yml',
]
depth_mult: 1.0
width_mult: 1.0

log_iter: 100
snapshot_epoch: 5
weights: output/yolov5_l_30e_obj365_finetune_coco/model_final
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/yolov5_l_300e_obj365.pdparams


TrainReader:
  batch_size: 16 # default 8 gpus, total bs = 128


YOLOv5Loss:
  obj_weight: 0.7
  cls_weght: 0.3


epoch: 30
LearningRate:
  base_lr: 0.001
  schedulers:
  - !YOLOv5LRDecay
    max_epochs: 30
    min_lr_ratio: 0.1
  - !ExpWarmup
    epochs: 3

OptimizerBuilder:
  optimizer:
    type: Momentum
    momentum: 0.937
    use_nesterov: True
  regularizer:
    factor: 0.0005
    type: L2
